server:
  port: 8090
spring:
  application:
    name: customer-service
  datasource:
    mongodb:
      host: localhost
      port: 27027
      database: customer_db
      authentication-database: admin
      username: jaures
      password: kameni
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
  instance:
    prefer-ip-address: true